version: "3.7"
services:
  dev:
    build:
      context: ../
      dockerfile: ./build/dev/Dockerfile
      target: dev
    command:  /usr/local/bin/init.sh
    volumes:
      - ../:/src
    working_dir: /src/
    environment:
      - BUILD_PROTO_ON_START=true
  auth:
    build: 
      context: ../
      dockerfile: ./build/auth/Dockerfile
      target: dev
    command: /go/bin/reflex -d fancy -c /etc/reflex.conf
    ports: 
      - 9090:9090
      - 8080:8080
    volumes:
      - ../:/src
    working_dir: /src/
    environment:
      - LOG_LEVEL=debug
      - ENABLE_GRPC=true
      - ENABLE_REST=true
      - REST_PORT=8080
      - ED_HOST=69.164.58.19
      - TOKEN_SECRET=testkey
    depends_on:
      - "dev"
  fake:
    build:
      context: ../
      dockerfile: ./build/fake/Dockerfile
      target: dev
    command: /go/bin/reflex -d fancy -c /etc/reflex.conf
    ports:
      - 9091:9091
      - 8081:8081
    volumes:
      - ../:/src
    working_dir: /src
    environment:
      - LOG_LEVEL=debug
      - ENABLE_GRPC=true
      - ENABLE_REST=true
      - REST_PORT=8081
      - REST_BACKEND=127.0.0.1:9091
      - GRPC_PORT=9091
      - AUTH_HOST=auth:9090
    depends_on:
      - "dev"
      - "auth"